apps/extras/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required
from .views import *

app_name = 'extras' 

urlpatterns = [
    path('listpaginas/', permission_required('users.extras')(login_required(ListPaginaView.as_view())), name='list_paginas'),
    path('createpaginas/', permission_required('users.extras')(login_required(CreatePaginaView.as_view())), name='create_paginas'),
    path('updatepaginas/<int:pk>/', permission_required('users.extras')(login_required(UpdatePaginaView.as_view())), name='update_paginas'),
    path('deletepagina/<int:pk>/', permission_required('users.users')(login_required(DeletePaginaView.as_view())), name='delete_pagina'),
   #miebros
    path('miembro/', permission_required('users.extras')(login_required(ListMiembroView.as_view())), name='miembro_list'),
    path('miembro/create/', permission_required('users.extras')(login_required(CreateMiembroView.as_view())), name='miembro_create'),
    path('miembro/update/<int:pk>/', permission_required('users.extras')(login_required(UpdateMiembroView.as_view())), name='miembro_update'),
    path('miembro/delete/<int:pk>/', permission_required('users.extras')(login_required(DeleteMiembroView.as_view())), name='miembro_delete'),
]

planipage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.publicaciones.urls','publicaciones'), namespace='publicaciones')),
    path('users/', include(('apps.users.urls', 'users'), namespace='users')),
    path('extras/', include(('apps.extras.urls', 'extras'), namespace='extras')),
    path('tipos/', include(('apps.tipos.urls', 'tipos'), namespace='tipos'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/extras/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.

class Miembro(models.Model):
	nombre = models.CharField(
		max_length=500,
		null=False,
		blank=False
	)
	apellidop = models.CharField(
		verbose_name='Apellido Paterno',
		max_length=500,
		null=False,
		blank=False
	)
	apellidom = models.CharField(
		verbose_name='Apellido Materno',
		max_length=500,
		null=False,
		blank=False
	)
	cargo = models.CharField(
		max_length=500,
		null=False,
		blank=False
	)
	prioridad = models.PositiveIntegerField(
		null=False,
		blank=False
	)
	class Meta:
		verbose_name = _('Miembro')
		verbose_name_plural = _('Miembros')
	def __str__(self):
		return self.nombre + " " + self.apellidop

class Pagina(models.Model):
	nombre = models.CharField(
		max_length=1000,
		null=False,
		blank=False
	)
	url = models.URLField(
		null=False,
		blank=False
	)
	class Meta:
		verbose_name = _('Pagina')
		verbose_name_plural = _('Paginas')
	def __str__(self):
		return self.nombre

apps/extras/forms.py
from django import forms
from .models import *

class PaginaForm(forms.ModelForm):
	class Meta:
		model = Pagina
		exclude = ['']
class MiembroForm(forms.ModelForm):
    class Meta:
        model = Miembro
        fields = ['nombre', 'apellidop', 'apellidom', 'cargo', 'prioridad']

apps/extras/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, FormView, DeleteView, DetailView
from apps.users.generic import *
from .forms import *

# Create your views here.

class ListPaginaView(ListSearchView):
	model = Pagina
	ordering = ['-id']
	paginate_by = 4
	template_name = 'pagina/pagina_list.html'
	fields_search = ['id', 'nombre']

class CreatePaginaView(CreateView, FormPageRedirectView):
	form_class = PaginaForm
	template_name = 'pagina/pagina_create.html'
	success_url = reverse_lazy('extras:list_paginas')
	#success_message = '%(nombre)s se creo correctamente'

class UpdatePaginaView(UpdateView, FormPageRedirectView):
	model = Pagina
	form_class = PaginaForm
	template_name = 'pagina/pagina_update.html'
	success_url = reverse_lazy('extras:list_paginas')

class DeletePaginaView(DeleteView):
	model = Pagina
	template_name = 'pagina/pagina_delete.html'
	success_url = reverse_lazy('extras:list_paginas')

#miembros
class ListMiembroView(ListSearchView):
    model = Miembro
    ordering = ['-prioridad', 'id']
    paginate_by = 4  
    template_name = 'miembro/miembro_list.html'
    fields_search = ['id', 'nombre', 'apellidop', 'apellidom', 'cargo']

class CreateMiembroView(CreateView, FormPageRedirectView):
    form_class = MiembroForm
    template_name = 'miembro/miembro_create.html'
    success_url = reverse_lazy('extras:miembro_list')

class UpdateMiembroView(UpdateView, FormPageRedirectView):
    model = Miembro
    form_class = MiembroForm
    template_name = 'miembro/miembro_update.html'
    success_url = reverse_lazy('extras:miembro_list') 

class DeleteMiembroView(DeleteView):
    model = Miembro
    template_name = 'miembro/miembro_delete.html'
    success_url = reverse_lazy('extras:miembro_list')  

apps/extras/templates/pagina/pagina_create.html
{% extends "base/base_form.html" %}
{% load gloval_tags %}
	{% block name %}
		<h2 class="text-center"> Crear {% get_model_verbose_name 'extras' 'Pagina' %}</h2>
	{% endblock name %}

apps/extras/templates/pagina/pagina_delete.html
{% extends "pagina/pagina_create.html" %}
{% load gloval_tags %}
	{% block name %}
		<h2 class="text-center"> Eliminar {% get_model_verbose_name 'extras' 'Pagina' %}</h2>
	{% endblock name %}

	{% block bodydelete %}
		<div class="alert alert-danger" role="alert">
		  Alerta se borrara el objeto {{object}}
		</div>
	{% endblock bodydelete %}

apps/extras/templates/pagina/pagina_list.html
{% extends "base/base_list.html" %}
{% load gloval_tags %}
	{% block headextra %}
		<a type="button" class="btn btn-primary" href="{% url 'extras:create_paginas' %}"><i class="fa-solid fa-plus"></i> Crear {% get_model_verbose_name 'extras' 'Pagina' %}</a>
	{% endblock headextra %}
	{% block bodylist %}
		<table class="table table-striped table-hover">
			<thead>
				<tr>
					<th scope="col">Id</th>
					<th scope="col">Nombre</th>
					<th scope="col">URL</th>
					<th scope="col">Opciones</th>
				</tr>
			</thead>
			<tbody>
				{% for object in object_list %}
					<tr id='{{ object.id}}' class="target-blink">
						<td>{{ object.id }}</td>
						<td>{{ object.nombre }}</td>
						<td>{{ object.url }}</td>
						<td>
							<div class="btn-group" role="group" aria-label="Basic example">
								<a type="button" class="btn btn-primary" href="{% url 'extras:update_paginas' object.id %}"><i class="fa-solid fa-pen-to-square"></i> Actualizar</a>
								<a type="button" class="btn btn-danger" href="{% url 'extras:delete_pagina' object.id %}"><i class="fa-solid fa-pen-to-square"></i> Eliminar</a>
							</div>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	{% endblock bodylist %}

apps/extras/templates/pagina/pagina_update.html
{% extends "pagina/pagina_create.html" %}
{% load gloval_tags %}
	{% block name %}
		<h2 class="text-center"> Actualizar {% get_model_verbose_name 'extras' 'Pagina' %}</h2>
	{% endblock name %}