apps/extras/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required
from .views import *

app_name = 'extras' 

urlpatterns = [
    path('listpaginas/', permission_required('users.extras')(login_required(ListPaginaView.as_view())), name='list_paginas'),
    path('createpaginas/', permission_required('users.extras')(login_required(CreatePaginaView.as_view())), name='create_paginas'),
    path('updatepaginas/<int:pk>/', permission_required('users.extras')(login_required(UpdatePaginaView.as_view())), name='update_paginas'),
    path('deletepagina/<int:pk>/', permission_required('users.users')(login_required(DeletePaginaView.as_view())), name='delete_pagina'),
   #miebros
    path('miembro/', permission_required('users.extras')(login_required(ListMiembroView.as_view())), name='miembro_list'),
    path('miembro/create/', permission_required('users.extras')(login_required(CreateMiembroView.as_view())), name='miembro_create'),
    path('miembro/update/<int:pk>/', permission_required('users.extras')(login_required(UpdateMiembroView.as_view())), name='miembro_update'),
    path('miembro/delete/<int:pk>/', permission_required('users.extras')(login_required(DeleteMiembroView.as_view())), name='miembro_delete'),
]

apps/publicaciones/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required
from .views import *
urlpatterns = [
    path('', main, name='main'),
    
    path('listpublicacion/', permission_required('users.publicaciones')(login_required(ListPublicacionViews.as_view())), name='publicacion_list'),
    path('createPublicacion/', permission_required('users.publicaciones')(login_required(CreatePublicacionView.as_view())), name='publicacion_create'),
    path('updatePublicacion/<int:pk>/', permission_required('users.publicaciones')(login_required(UpdatePublicacionView.as_view())), name='publicacion_update'),
    path('deletePublicacion/<int:pk>/', permission_required('users.publicaciones')(login_required(DeletePublicacionView.as_view())), name='publicacion_delete'),

    path('archivoforminline/<int:pk>/', permission_required('users.publicaciones')(login_required(archivo_form_inline_view)), name='publicaciones_inline'),

    path('listvistapublicaiones/<int:pk>/', ListVistaPublicaionesView.as_view(), name='list_vistapublicaciones'),
    path('listsearch/', ListSearchPublicaionView.as_view(), name='list_search'),
    path('detailpublicacion/<int:pk>/', DetailPublicacionView.as_view(), name='detail_publicacion'),
    path('nosotros/', nosotros_view, name='nosotros')
]

apps/tipos/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required
from .views import *

urlpatterns = [ 
    path('listmaestro/', permission_required('users.tipos')(login_required(ListTipoMaestroView.as_view())), name='maestro_list'),
    path('createmaestro/', permission_required('users.tipos')(login_required(CreateTipoMaestroView.as_view())), name='maestro_create'),
    path('updatemaestro/<int:pk>/', permission_required('users.tipos')(login_required(UpdateTipoMaestroView.as_view())), name='maestro_update'),
    path('deletemaestro/<int:pk>/', permission_required('users.tipos')(login_required(DeleteTipoMaestroView.as_view())), name='maestro_delete'),
    
    path('tipolist/<int:pk>/', permission_required('users.tipos')(login_required(ListTipoView.as_view())), name='tipo_list'),
    path('createtipo/<int:pk>', permission_required('users.tipos')(login_required(TipoCreateView.as_view())), name='tipo_create'),
    path('updatetipo/<int:pk>/', permission_required('users.tipos')(login_required(TipoUpdateView.as_view())), name='tipo_update'),
    path('deletetipo/<int:pk>/', permission_required('users.tipos')(login_required(TipoDeleteView.as_view())), name='tipo_delete'),
]

apps/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, logout_then_login, PasswordResetView
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    path('login/',
        LoginView.as_view(template_name='auth/login.html'),
        name='login'
    ),
    path('logout/',
        logout_then_login,
        name='logout'
    ),
    path('listuser/', permission_required('users.users')(login_required(ListUserView.as_view())), name='list_user'),
    path('createuser/', permission_required('users.users')(login_required(CreateUserView.as_view())), name='create_user'),
    path('permisos/<int:pk>/', permission_required('users.users')(login_required(PermisosView.as_view())), name='user_permisos'),
    path('constantes/', permission_required('users.users')(login_required(ConstanceView.as_view())), name='constantes')
]

planipage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.publicaciones.urls','publicaciones'), namespace='publicaciones')),
    path('users/', include(('apps.users.urls', 'users'), namespace='users')),
    path('extras/', include(('apps.extras.urls', 'extras'), namespace='extras')),
    path('tipos/', include(('apps.tipos.urls', 'tipos'), namespace='tipos'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/base_form.html
{% extends "base/center_body.html" %}
{% load crispy_forms_tags %}
{% load gloval_tags %}
	{% block contend %}
		<div class="card">
			<div class="card-header">
				{% block name %}

				{% endblock name %}
				{% block headextra %}
					
				{% endblock headextra %}
			</div>
			<div class="card-body">
				{% block bodyform %}
					<form  method="post" class="form" enctype="multipart/form-data">
						{% csrf_token %}

						{% block bodydelete %}
							
						{% endblock bodydelete %}
						
						{{ form|crispy }}
						<div class="d-flex justify-content-center">
							<button type="submit" class="btn btn-primary"><i class="fa-solid fa-floppy-disk"></i> Guardar</button>
						</div>
					</form>
				{% endblock bodyform %}
			</div>
		</div>
		{% block extra %}
			
		{% endblock extra %}
	{% endblock contend %}

templates/base/base_list.html
{% extends "base/center_body.html" %}
{% load gloval_tags %}
	{% block contend %}
		<div class="card">
			<div class="card-header">
				{% block name %}
					<h2 class="text-center">Lista de {{ view|verbose_name_plural }}</h2>
				{% endblock name %}
				{% block headextra %}
					
				{% endblock headextra %}
			</div>
			<div class="card-body">
				{% if form %}
					{% include "base/base_searchform.html" %}
				{% endif %}
				<div class="table-responsive-md">
					{% block bodylist %}
						
					{% endblock bodylist %}
				</div>
				{% if not object_list %}
					<h3 class="text-center">No Existen Objetos Creados</h3>
				{% endif %}
			</div>
			{% include "base/base_paginador.html" %}
		</h2>
	{% endblock contend %}

templates/base/base_main.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>DPU</title>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
		<link rel="stylesheet" href="{% static 'styles.css' %}">
		<link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
		<script src="https://kit.fontawesome.com/9328387887.js" crossorigin="anonymous"></script>
		<script src="{% static 'tinymce/js/tinymce/tinymce.min.js' %}" referrerpolicy="origin"></script>
		<link href="https://fonts.cdnfonts.com/css/times-new-roman" rel="stylesheet">

		<!-- Google tag (gtag.js) -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=G-3NJXM405CD"></script>
		<script>
		  window.dataLayer = window.dataLayer || [];
		  function gtag(){dataLayer.push(arguments);}
		  gtag('js', new Date());

		  gtag('config', 'G-3NJXM405CD');
		</script>
	</head>
	<body>
		{% block wave %}
			{% include "base/wave.html" %}
		{% endblock wave %}

		{% block navbar %}
			{% include 'base/nav_bar.html' %}
		{% endblock navbar %}	
		
		{% block body %}
			
		{% endblock body %}
		
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
		<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
		<script src="{% static 'scripts.js' %}"></script>

		{% block scripts %}
			
		{% endblock scripts %}
		
		<script>
			tinymce.init({
				selector: 'textarea',
				//plugins: 'advlist link image lists',
				language: 'es',
				plugins: [
					'advlist', 'autolink', 'lists', 'link', 'image', 'charmap', 'preview',
					'anchor', 'searchreplace', 'visualblocks', 'code', 'fullscreen',
					'insertdatetime', 'media', 'table', 'help', 'wordcount'
				],
				toolbar: 'undo redo | blocks | ' +
				'bold italic backcolor | alignleft aligncenter ' +
				'alignright alignjustify | bullist numlist outdent indent | ' +
				'removeformat | help',
				license_key: 'gpl'
			});
			document.querySelectorAll('textarea').forEach(elemt=>{
				elemt.required = false;
			});
		</script>

		<script>
			have_search = new URLSearchParams(window.location.search);
			if(have_search.get("search")){
				document.getElementById("search-form").value = have_search.get("search");
			}
			console.log(have_search.get("search"));
		</script>
	</body>
</html>

templates/base/base_paginador.html
{% if is_paginated %}
	<div class="d-flex justify-content-center">
		<ul class="pagination">
			{% if page_obj.has_previous %}
				<li class="page-item">
					<a class="page-link" href="{% querystring page=page_obj.previus_page_number %}">Anterior</a>
				</li>
			{% endif %}

			<li class="page-item">
		    	<div class="page-link">
					<form role="form" method="get" style="display: inline-flex;">
						{% if request.GET %}
							{% for key, value in request.GET.items %}
								{% if key != 'page' %}
									<input type="hidden" name="{{key}}" value="{{value}}">
								{% endif %}
							{% endfor %}
						{% endif %}
						<input autocomplete="off" style="width: 30px; height: 20px;" type="text" name="page" value="{{ page_obj.number }}">
					</form>
					de {{ page_obj.paginator.num_pages }}.
				</div>
			</li>
			
			{% if page_obj.has_next %}
				<li class="page-item">
					<a class="page-link" href="{% querystring page=page_obj.next_page_number %}">Siguiente</a>
				</li>
			{% endif %}
		</ul>
	</div>
{% endif %}

templates/base/base_searchform.html
{% load crispy_forms_tags %}
<form method="GET" action="{{ request.path }}" class="pb-3" id="formlist">
	{% crispy form %}
	<button type="submit" class="no-show">Enviar</button>
</form>

templates/base/center_body.html
{% extends "base/base_main.html" %}
	{% block body %}
		<div class="pt-5 pb-5">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-md-12">
						{% block contend %}
							
						{% endblock contend %}
					</div>
				</div>
			</div>
		</div>
	{% endblock body %}

templates/base/nav_bar.html
{% load gloval_tags %}
<nav class="navbar navbar-expand-lg bg-personal" data-bs-theme="dark">
	<div class="container-fluid">
		<a class="navbar-brand" href="/">Planificacion</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar2" aria-controls="offcanvasNavbar2">
	        <span class="navbar-toggler-icon"></span>
	     </button>
		<div class="offcanvas offcanvas-start text-bg-dark" tabindex="-1" id="offcanvasNavbar2" aria-labelledby="offcanvasNavbar2Label">
        <div class="offcanvas-header">
			<h5 class="offcanvas-title" id="offcanvasNavbar2Label">Offcanvas</h5>
			<button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
        	{% comment %}
        		
        	{% endcomment %}
			<ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
				<li class="nav-item">
					<a class="nav-link" target="_blank" aria-current="page" href="{% url 'publicaciones:nosotros' %}">Nosotros</a>
				</li>

				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
					    Paginas de Interés
					</a>
					<ul class="dropdown-menu">
						{% for p in request.paginas %}
							<li><a class="dropdown-item" href="{{ p.url }}"><i class="fa-solid fa-globe"></i> {{ p.nombre }}</a></li>
						{% endfor %}
					</ul>
				</li>

				{% for tm in request.tipo_maestro %}
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
						    {{ tm.nombre }}
						</a>
						<ul class="dropdown-menu">
							{% for t in tm.tipo_set.all %}
								<li><a class="dropdown-item" href="{% url 'publicaciones:list_vistapublicaciones' t.pk %}"><i class="fa-solid fa-list"></i> {{ t.nombre }}</a></li>
							{% endfor %}
						</ul>
					</li>
				{% endfor %}

				{% if user.is_authenticated %}
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
						    Opciones
						</a>
						<ul class="dropdown-menu">
							{% if perms.users.users %}
								<li><a class="dropdown-item" href="{% url 'users:list_user' %}"><i class="fa-solid fa-list"></i> Lista de  {% get_model_verbose_name_plural 'users' 'User' %}</a></li>
								<li><a class="dropdown-item" href="{% url 'users:constantes' %}"><i class="fa-solid fa-list"></i> Constantes</a></li>
							{% endif %}
							{% if perms.users.extras %}
								<li><a class="dropdown-item" href="{% url 'extras:list_paginas' %}"><i class="fa-solid fa-list"></i> Lista de  {% get_model_verbose_name_plural 'extras' 'Pagina' %}</a></li>
								<li><a class="dropdown-item" href="{% url 'extras:miembro_list' %}"><i class="fa-solid fa-list"></i> Lista de {% get_model_verbose_name_plural 'extras' 'Miembro' %}</a></li>
							{% endif %}
							{% if perms.users.tipos %}
								<li><a class="dropdown-item" href="{% url 'tipos:maestro_list' %}"><i class="fa-solid fa-list"></i> Lista de {% get_model_verbose_name_plural 'tipos' 'TipoMaestro' %}</a></li>
							{% endif %}
							{% if perms.users.publicaciones %}
								<li><a class="dropdown-item" href="{% url 'publicaciones:publicacion_list' %}"><i class="fa-solid fa-list"></i> Lista de {% get_model_verbose_name_plural 'publicaciones' 'Publicacion' %}</a></li>
							{% endif %}
						    <li>
						      <hr class="dropdown-divider">
						    </li>
						    <li>
								<form action="{% url 'users:logout' %}" method="post">
									{% csrf_token %}
									<a class="dropdown-item" onclick="this.closest('form').submit();return false;">
										<i class="fa-solid fa-right-from-bracket"></i> Salir
									</a>
								</form>
							</li>
						</ul>
					</li>
				{% endif %}

			</ul>

			<form class="d-flex mt-3 mt-lg-0" action="{% url 'publicaciones:list_search' %}" method="GET">
				<input type="search" id="search-form" name='search' class="form-control me-2" type="search" placeholder="Buscar..." aria-label="Search">
				<button class="btn btn-outline-success" type="submit">Search</button>
			</form>

        </div>
      </div>
    </div>
</nav>

templates/base/wave.html
<div>
    <div class="wave"></div>
    <div class="wave"></div>
    <div class="wave"></div>
 </div>