apps/tipos/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required
from .views import *

urlpatterns = [ 
    path('listmaestro/', permission_required('users.tipos')(login_required(ListTipoMaestroView.as_view())), name='maestro_list'),
    path('createmaestro/', permission_required('users.tipos')(login_required(CreateTipoMaestroView.as_view())), name='maestro_create'),
    path('updatemaestro/<int:pk>/', permission_required('users.tipos')(login_required(UpdateTipoMaestroView.as_view())), name='maestro_update'),
    path('deletemaestro/<int:pk>/', permission_required('users.tipos')(login_required(DeleteTipoMaestroView.as_view())), name='maestro_delete'),
    
    path('tipolist/<int:pk>/', permission_required('users.tipos')(login_required(ListTipoView.as_view())), name='tipo_list'),
    path('createtipo/<int:pk>', permission_required('users.tipos')(login_required(TipoCreateView.as_view())), name='tipo_create'),
    path('updatetipo/<int:pk>/', permission_required('users.tipos')(login_required(TipoUpdateView.as_view())), name='tipo_update'),
    path('deletetipo/<int:pk>/', permission_required('users.tipos')(login_required(TipoDeleteView.as_view())), name='tipo_delete'),
]

planipage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.publicaciones.urls','publicaciones'), namespace='publicaciones')),
    path('users/', include(('apps.users.urls', 'users'), namespace='users')),
    path('extras/', include(('apps.extras.urls', 'extras'), namespace='extras')),
    path('tipos/', include(('apps.tipos.urls', 'tipos'), namespace='tipos'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/tipos/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.

class TipoMaestro(models.Model):
	nombre = models.CharField(
		max_length=1000,
		null=False,
		blank=False
	)
	prioridad = models.PositiveIntegerField(
		null=False,
		blank=False
	)
	def __str__(self):
		return self.nombre
	class Meta:
		verbose_name = _('Tipo Maestro')
		verbose_name_plural = _('Tipos Maestros')

class Tipo(models.Model):
	tipomaestro = models.ForeignKey('tipos.TipoMaestro', on_delete=models.CASCADE)
	nombre = models.CharField(
		max_length=1000,
		null=False,
		blank=False
	)
	prioridad = models.PositiveIntegerField(
		null=False,
		blank=False
	)
	in_main = models.BooleanField(
		verbose_name='En Main',
		null=False,
		blank=False,
		default=False
	)
	def __str__(self):
		return self.nombre
	class Meta:
		verbose_name = _('Tipo')
		verbose_name_plural = _('Tipos')

apps/tipos/forms.py
from django import forms
from .models import *

class TipoMaestroForm(forms.ModelForm):
    class Meta:
        model = TipoMaestro
        exclude = ['']

class TipoForm(forms.ModelForm):
    class Meta:
        model = Tipo
        exclude = ['tipomaestro']

apps/tipos/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, FormView, DeleteView, DetailView
from apps.users.generic import *
from .forms import *


# Create your views here.
class ListTipoMaestroView(ListSearchView):
    model = TipoMaestro
    ordering = ['-id']
    paginate_by = 10
    template_name = 'tipomaestro/tipomaestro_list.html'
    fields_search = ['id', 'nombre']

class CreateTipoMaestroView(CreateView, FormPageRedirectView):
    model = TipoMaestro
    form_class = TipoMaestroForm
    template_name = 'tipomaestro/tipomaestro_create.html'
    success_url = reverse_lazy('tipos:maestro_list')

class UpdateTipoMaestroView(UpdateView, FormPageRedirectView):
    model = TipoMaestro
    form_class = TipoMaestroForm
    template_name = 'tipomaestro/tipomaestro_update.html'
    success_url = reverse_lazy('tipos:maestro_list')

class DeleteTipoMaestroView(DeleteView):
    model = TipoMaestro
    template_name = 'tipomaestro/tipomaestro_delete.html'
    success_url = reverse_lazy('tipos:maestro_list')

#tipo
class ListTipoView(ListSearchView, ModelExtraView):
    model_extra = TipoMaestro
    model = Tipo
    ordering = ['-id']
    paginate_by = 10
    template_name = 'tipo/tipo_list.html'
    fields_search = ['id', 'nombre']
    def get_queryset(self):
        query = super().get_queryset()
        return query.filter(tipomaestro=self.kwargs['pk'])

class TipoCreateView(FormPageRedirectView, CreateViewInternal):
    model_extra = TipoMaestro
    form_class = TipoForm
    template_name = 'tipo/tipo_create.html'
    success_url = 'tipos:tipo_list'
    location = 'tipomaestro_id'

class TipoUpdateView(FormPageRedirectView, UpdateViewInternal):
    model = Tipo
    form_class = TipoForm
    template_name = 'tipo/tipo_update.html'
    success_url = 'tipos:tipo_list'
    location = 'tipomaestro_id'

class TipoDeleteView(DeleteViewInternal):
    model = Tipo
    template_name = 'tipo/tipo_delete.html'
    success_url = 'tipos:tipo_list'
    location = 'tipomaestro_id'

apps/tipos/templates/tipo/tipo_create.html
{% extends "base/base_form.html" %}
{% load gloval_tags %}
	{% block name %}
		<h2 class="text-center"> Crear {% get_model_verbose_name 'tipos' 'Tipo' %}</h2>
		<div class="alert alert-info mt-2" role="alert">
            <span class="badge text-bg-info"><strong>{% get_model_verbose_name 'tipos' 'TipoMaestro' %}:</strong> {{ object_extra }}</span>
        </div>
	{% endblock name %}

apps/tipos/templates/tipo/tipo_delete.html
{% extends "tipo/tipo_create.html" %}
{% load gloval_tags %}
	{% block name %}
		<h2 class="text-center"> Eliminar {% get_model_verbose_name 'tipos' 'Tipo' %}</h2>
		<div class="alert alert-info mt-2" role="alert">
            <span class="badge text-bg-info"><strong>{% get_model_verbose_name 'tipos' 'TipoMaestro' %}:</strong> {{ object.tipomaestro }}</span>
        </div>
	{% endblock name %}

	{% block bodydelete %}
		<div class="alert alert-danger" role="alert">
		  Alerta se borrara el objeto {{object}}
		</div>
	{% endblock bodydelete %}

apps/tipos/templates/tipo/tipo_list.html
{% extends "base/base_list.html" %}
{% load gloval_tags %}
	{% block headextra %}
        <a type="button" class="btn btn-primary" href="{% url 'tipos:tipo_create' view.kwargs.pk %}">
        <i class="fa-solid fa-plus"></i> Crear {% get_model_verbose_name 'tipos' 'Tipo' %}</a>
        <div class="alert alert-info mt-2" role="alert">
            <span class="badge text-bg-info"><strong>{% get_model_verbose_name 'tipos' 'TipoMaestro' %}:</strong> {{ object_extra }}</span>
        </div>
	{% endblock headextra %}
	{% block bodylist %}
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Prioridad</th>
                    <th scope="col">Maestro</th>
                    <th scope="col">En Main</th>
                    <th scope="col">Opciones</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                    <tr id='{{ object.id}}' class="target-blink">
                        <td>{{ object.id }}</td>
                        <td>{{ object.nombre }}</td>
                        <td>{{ object.prioridad }}</td>
                        <td>{{ object.tipomaestro }}</td>
                        <td>
                            {% if object.in_main %}
                                <span class="badge rounded-pill text-bg-success">Si</span>
                            {% else %}
                                <span class="badge rounded-pill text-bg-warning">No</span>
                            {% endif %}
                        </td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a type="button" class="btn btn-primary" href="{% url 'tipos:tipo_update' object.id %}">
                                    <i class="fa-solid fa-pen-to-square"></i> Actualizar
                                </a>
                                <a type="button" class="btn btn-danger" href="{% url 'tipos:tipo_delete' object.id %}">
                                    <i class="fa-solid fa-trash"></i> Eliminar
                                </a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}    
            </tbody>
        </table>    
    {% endblock bodylist %}

apps/tipos/templates/tipo/tipo_update.html
{% extends "tipo/tipo_create.html" %}
{% load gloval_tags %}
	{% block name %}
		<h2 class="text-center"> Actualizar {% get_model_verbose_name 'tipos' 'Tipo' %}</h2>
		<div class="alert alert-info mt-2" role="alert">
            <span class="badge text-bg-info"><strong>{% get_model_verbose_name 'tipos' 'TipoMaestro' %}:</strong> {{ object.tipomaestro }}</span>
        </div>
	{% endblock name %}